package no.uio.ifi.in2000.team7.boatbuddy.model.metalerts

data class Properties(
    val altitude_above_sea_level: Int,
    val area: String,
    val awarenessResponse: String,
    val awarenessSeriousness: String? = null,
    val awareness_level: String,
    val awareness_type: String,
    val ceiling_above_sea_level: Int,
    val certainty: String,
    val consequences: String? = null,
    val contact: String,
    val county: List<String>,
    val description: String,
    val event: String,
    val eventAwarenessName: String? = null,
    val eventEndingTime: String? = null,
    val geographicDomain: String,
    val id: String,
    val incidentName: String? = null,
    val instruction: String,
    val municipality: List<String>,
    val resources: List<Resource>,
    val riskMatrixColor: String,
    val severity: String,
    val status: String,
    val title: String,
    val triggerLevel: String? = null,
    val type: String,
    val web: String
)